name: homeassistant - check_for_new_version

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "30 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-version:
    runs-on: [self-hosted, X64]
    steps:
      - name: check_version
        id: check_version
        run: |
          latest_version=$(curl -s "https://hub.docker.com/v2/repositories/homeassistant/home-assistant/tags/" |   jq -r '.results[] | select(.name | test("^[0-9]{4}\\.[0-9]{2}\\.[0-9]+$")) | .name' |   sort -V | tail -n1)

          if [ "$latest_version" != "${{ vars.HA_VERSION }}" ]; then
            echo "New version found: $latest_version"

            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/HA_NEW_VERSION_FOUND \
              -d "{\"name\":\"HA_NEW_VERSION_FOUND\",\"value\":\"true\"}"
              
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/HA_VERSION \
              -d "{\"name\":\"HA_VERSION\",\"value\":\"$latest_version\"}"
              
          else
            echo "No new version found."
            
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/HA_NEW_VERSION_FOUND \
              -d "{\"name\":\"HA_NEW_VERSION_FOUND\",\"value\":\"false\"}"
              
          fi
