name: duoauthproxy - build_docker_image

env:
  GIT_SUBDIR: duoauthproxy
  REGISTRY: pcr.jlv6.com:443
  
on:
  workflow_run:
    workflows: ["duoauthproxy - check_for_new_version"]
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ vars.DUO_NEW_VERSION_FOUND }} == "true"
    runs-on: [self-hosted, X64]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to pcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PCR_USERNAME }}
          password: ${{ secrets.PCR_PASSWORD }}
      - name: extract metadata for the docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/arc-${{ env.GIT_SUBDIR }}"
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ env.GIT_SUBDIR }}"
          push: true
          platforms: linux/amd64
          tags: |
            "${{ env.REGISTRY }}/arc-${{ env.GIT_SUBDIR }}:latest"
            "${{ env.REGISTRY }}/arc-${{ env.GIT_SUBDIR }}:${{ vars.DUO_VERSION }}"
