name: duoauthproxy - check_for_new_version

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - self-hosted
    steps:
      - name: Update secrets
        run: |
          APP_VERSION=$(curl -s -I -L "https://dl.duosecurity.com/duoauthproxy-latest-src.tgz" | grep -i "content-disposition" | awk -F'filename="' '{print $2}' | awk -F'"' '{print $1}' | awk -F'-' '{print $2}')
          if [ "$APP_VERSION" != "${{ vars.DUO_VERSION }}" ]; then
            echo "New version found: $APP_VERSION"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"DUO_NEW_VERSION_FOUND\",\"value\":\"true\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/DUO_NEW_VERSION_FOUND
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"DUO_VERSION\",\"value\":\"$APP_VERSION\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/DUO_VERSION
          else
            echo "No new version found."
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"DUO_NEW_VERSION_FOUND\",\"value\":\"false\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/DUO_NEW_VERSION_FOUND
          fi
