name: duoauthproxy - build_docker_image

env:
  GIT_SUBDIR: duoauthproxy
  REGISTRY_IMAGE: "${{ secrets.FORGEJO_REGISTRY01 }}/${{ secrets.FORGEJO_OWNER01 }}/arc-duoauthproxy"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["duoauthproxy - check_for_new_version"]
    branches: ["main"]
    types: ["completed"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  debug:
    runs-on: self-hosted
    steps:
      - name: print var DUO_NEW_VERSION_FOUND
        run: echo "DUO_NEW_VERSION_FOUND value is ${{ vars.DUO_NEW_VERSION_FOUND }}" 

  build-image:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: x64
          - platform: arm64
            runner: arm64
    runs-on: ${{ matrix.runner }}
    needs: debug
    if: ${{ vars.DUO_NEW_VERSION_FOUND == 'true' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.FORGEJO_REGISTRY01 }}
          username: ${{ secrets.FORGEJO_USER01 }}
          password: ${{ secrets.FORGEJO_USER01_PAT }}

      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.GIT_SUBDIR }}"
          platforms: linux/${{ matrix.platform }}
          file: Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.platform }}
          tags: |
            "${{ env.REGISTRY_IMAGE }}:${{ vars.DUO_VERSION }}-${{ matrix.platform }}"

  merge:
    runs-on: self-hosted
    needs: build-image

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.FORGEJO_REGISTRY01 }}
          username: ${{ secrets.FORGEJO_USER01 }}
          password: ${{ secrets.FORGEJO_USER01_PAT }}

      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY_IMAGE }}:${{ vars.DUO_VERSION }} \
            ${{ env.REGISTRY_IMAGE }}:${{ vars.DUO_VERSION }}-amd64 \
            ${{ env.REGISTRY_IMAGE }}:${{ vars.DUO_VERSION }}-arm64

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ vars.DUO_VERSION }}
