name: haproxy - build_docker_image

env:
  APP: haproxy
  REGISTRY_IMAGE: ghcr.io/v6Org01/arc-haproxy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["haproxy - check_for_new_version"]
    branches: ["main"]
    types: ["completed"]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  debug:
    runs-on: self-hosted
    steps:
      - name: print var HAPROXY_NEW_VERSION_FOUND
        run: echo "HAPROXY_NEW_VERSION_FOUND value is ${{ vars.HAPROXY_NEW_VERSION_FOUND }}" 

  build-image:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: x64
          - platform: arm64
            runner: arm64
    runs-on: ${{ matrix.runner }}
    needs: debug
    if: ${{ vars.HAPROXY_NEW_VERSION_FOUND == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.APP }}"
          platforms: linux/${{ matrix.platform }}
          file: Dockerfile
          push: true
          cache-from: type=gha,scope=build-${{ env.APP }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ env.APP }}-${{ matrix.platform }}
          provenance: false
          tags: |
            "${{ env.REGISTRY_IMAGE }}:${{ vars.HAPROXY_VERSION }}-${{ matrix.platform }}"

  build-merge:
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY_IMAGE }}:${{ vars.HAPROXY_VERSION }} \
            ${{ env.REGISTRY_IMAGE }}:${{ vars.HAPROXY_VERSION }}-amd64 \
            ${{ env.REGISTRY_IMAGE }}:${{ vars.HAPROXY_VERSION }}-arm64
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ vars.HAPROXY_VERSION }}
