name: keepalived - check_for_new_version

env:
  APP: keepalived

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.APP }}"
          file: DockerfileVersion
          push: false
          load: true  # automatically loads the single-platform build result to docker images (for use in next step).
          cache-from: type=gha,scope=build-${{ env.APP }}-${{ runner.arch }}
          cache-to: type=gha,mode=max,scope=build-${{ env.APP }}-${{ runner.arch }}
          tags: version-image:latest
      - name: Run container
        id: run-container
        run: |
          APP_VERSION=$(docker run --rm version-image:latest)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_OUTPUT
      - name: Update secrets
        run: |
          if [ "${{ steps.run-container.outputs.APP_VERSION }}" != "${{ vars.KEEPALIVED_VERSION }}" ]; then
            echo "New version found: ${{ steps.run-container.outputs.APP_VERSION }}"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"KEEPALIVED_NEW_VERSION_FOUND\",\"value\":\"true\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/KEEPALIVED_NEW_VERSION_FOUND
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"KEEPALIVED_VERSION\",\"value\":\"${{ steps.run-container.outputs.APP_VERSION }}\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/KEEPALIVED_VERSION
          else
            echo "No new version found."
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"KEEPALIVED_NEW_VERSION_FOUND\",\"value\":\"false\"}" \
              https://api.github.com/repos/elaurensx/dockerbuild/actions/variables/KEEPALIVED_NEW_VERSION_FOUND
          fi
