name: check-version-opentelemetry-network-build-tools

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - gha-runner-scale-set-arm64
    steps:
      - name: Check version
        uses: v6Org01/.github/actions/get-latestTagUpdateTimestamp-dockerhub@main
        with:
          APPLICATION: OPENTELEMETRY_NETWORK_BUILD_TOOLS
          DOCKERHUB_REPO: otel/opentelemetry-network-build-tools
          GITHUB_REPO: v6Org01/dockerbuild
          GITHUB_PAT_DEFAULT: ${{ secrets.PAT_DEFAULT }}
