name: build-push-opentelemetry-network-build-tools

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["trigger-wf-pushImage2Registry-OPENTELEMETRY_NETWORK_BUILD_TOOLS"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  build-image-push:
    uses: v6Org01/.github/.github/workflows/buildPushImage.yaml@main
    with:
      APPLICATION: opentelemetry-network-build-tools
      BUILD_ARGS: |
        REGISTRY=${{ vars.REGISTRY_PRIVATE_PULL }}
      PUSH_TO_PUBLIC: false
      PUSH_TO_PRIVATE: true
      OWNER: ${{ vars.OWNER }}
      REGISTRY_PRIVATE: ${{ vars.REGISTRY_PRIVATE }}
      REGISTRY_PRIVATE_PULL: ${{ vars.REGISTRY_PRIVATE_PULL }}
      REGISTRY_PUBLIC: ${{ vars.REGISTRY_PUBLIC }}
      VERSION: ${{ vars.DUO_VERSION }}
    secrets:
      REGISTRY_PRIVATE_USER: ${{ secrets.REGISTRY_PRIVATE_USER01 }}
      REGISTRY_PRIVATE_PASSWD: "${{ secrets.REGISTRY_PRIVATE_USER01_PASSWD }}"
      REGISTRY_PUBLIC_USER: ${{ github.actor }}
      REGISTRY_PUBLIC_PASSWD: ${{ secrets.PAT_PACKAGES }}
